classdef tIntegration < matlab.unittest.TestCase
%TINTEGRATION End-to-end smoke test for runPalletizingControlLoop.m
%
%   Runs the full pipeline in "mock" RTDE mode with minimal iterations so
%   it completes quickly in CI. Does NOT require any toolboxes beyond base
%   MATLAB (uses greedy optimizer and mock RTDE).

    methods (TestMethodSetup)
        function addPaths(tc) %#ok<MANU>
            addpath(genpath(fullfile(fileparts(fileparts(mfilename('fullpath'))), 'src')));
            addpath(genpath(fullfile(fileparts(fileparts(mfilename('fullpath'))), 'data')));
        end
    end

    methods (Test)
        function testPredefinedModeRunsToCompletion(tc)
            results = runPalletizingControlLoop( ...
                'Mode', 'predefined', ...
                'OptimizerType', 'greedy', ...
                'RTDEMode', 'mock', ...
                'Visualize', false, ...
                'Verbose', false);

            tc.verifyTrue(isstruct(results), 'Results must be a struct.');
            tc.verifyTrue(istable(results.layout), 'layout must be a table.');
            tc.verifyTrue(results.collisionCheck.isValid, ...
                ['Layout collision check failed: ', ...
                 strjoin(results.collisionCheck.issues, '; ')]);
            tc.verifyGreaterThan(results.optimizerInfo.utilization, 0, ...
                'At least some boxes should be placed.');
        end

        function testRealtimeModeRunsToCompletion(tc)
            results = runPalletizingControlLoop( ...
                'Mode', 'realtime', ...
                'NumBoxes', 5, ...
                'Seed', 7, ...
                'OptimizerType', 'greedy', ...
                'RTDEMode', 'mock', ...
                'Visualize', false, ...
                'Verbose', false);

            tc.verifyEqual(height(results.boxes), 5);
            tc.verifyTrue(results.collisionCheck.isValid, ...
                ['Real-time layout collision check failed: ', ...
                 strjoin(results.collisionCheck.issues, '; ')]);
        end

        function testRtdeCommandLogPopulated(tc)
            results = runPalletizingControlLoop( ...
                'Mode', 'predefined', ...
                'OptimizerType', 'greedy', ...
                'RTDEMode', 'mock', ...
                'Visualize', false, ...
                'Verbose', false);

            % At least one movel command per placed box.
            numPlaced = sum(results.layout.placed);
            tc.verifyGreaterThanOrEqual(numel(results.rtdeCommandLog), numPlaced, ...
                'Expected at least one command per placed box.');
        end

        function testTrajectoryStructure(tc)
            results = runPalletizingControlLoop( ...
                'Mode', 'predefined', ...
                'OptimizerType', 'greedy', ...
                'RTDEMode', 'mock', ...
                'Visualize', false, ...
                'Verbose', false);

            for k = 1:numel(results.trajectories)
                t = results.trajectories(k);
                tc.verifyTrue(isfield(t, 'id'));
                tc.verifyTrue(isfield(t, 'trajectory'));
                tc.verifyTrue(isfield(t, 'success'));
            end
        end
    end
end
